[package]
name = "iroh-util"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Utilities for iroh"

[dependencies]
cid = "0.8.4"
ctrlc = "3.2.2"
futures = "0.3.21"
anyhow = "1.0.57"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
config = "0.13.1"
tracing = "0.1.34"
temp-env = "0.3.1"
rlimit = "0.8.3"
dirs-next = "2.0.0"